version: "3.9"

services:
  mongo:
    container_name: mongo_db
    image: mongo:4.2
    volumes:
      - data:/var/lib/mysql
    ports:
      - 27017:27017
    command: mongod --auth

volumes:
  data: